"""
Backend Internationalisation (i18n)
-----------------------------------
Provides translated strings for PDF reports, Matplotlib plot labels and
any other server-side text.  Exoplot is intentionally **strictly
bilingual** (English + French) — the frontend language toggle only
exposes those two locales, and this module mirrors that contract.

Keys are split into two logical groups:

* ``report_*`` / ``section_*`` / ``col_*`` / ``obs_*`` / ``derived_*``
  / axis labels (``time_bjd``, ``normalized_flux``, …)
      — consumed by the long-form PDF report in ``modules/reports.py``.
* ``ui_*``
      — consumed by the **analysis SPA** plot helpers in
      ``routers/analysis.py`` (short titles, vibrant academic labels).

Usage::

    from modules.i18n import t, set_locale
    set_locale("fr")
    t("report_title")              # → "Rapport d'Analyse de Transit"
    t("ui_title_raw_lc", "en")     # → "Stitched raw lightcurve"

Author: S. Wittmann
Repository: https://github.com/SimonWtmn/Exoplot
"""

_STRINGS: dict[str, dict[str, str]] = {
    # ══════════════════════════════════════════════════════════════
    #  English (reference pack — every new key must first land here)
    # ══════════════════════════════════════════════════════════════
    "en": {
        # Report structure
        "report_title": "Transit Analysis Report",
        "report_header": "Exoplot Report",
        "made_by": "Made by {url}  \u2022  {date}",
        "page_summary": "Transit Fit Summary",
        "page_diagnostics": "MCMC Diagnostics",
        "generated_by": "Generated by {name}",
        "generated_on": "Generated on {date}",
        "target_label": "Target: {target}",

        # Report-page section headings
        "section_lightcurve": "Cleaned Lightcurve",
        "section_raw_lightcurve": "Raw Light Curve (SAP / PDCSAP)",
        "section_periodogram": "Box Least Squares Periodogram",
        "section_transit_fit": "Phase-Folded Transit (P = {period:.4f} d)",
        "section_parameters": "Derived Parameters",
        "section_pixel_file": "Target Pixel File (film strip)",
        "section_spaghetti": "Posterior Spaghetti Plot",
        "section_mcmc_results": "MCMC Results",
        "section_fit_quality": "Fit Quality",
        "tpf_unavailable": "Target pixel file unavailable",
        "tpf_median_label": "Median",
        "tpf_frame_label": "t = {t:.3f} d",
        "tpf_aperture_label": "Pipeline aperture",
        "tpf_movie_title": "Target Pixel File — Frame-by-frame Movie",
        "tpf_movie_frame": "Frame {i}/{n}  \u2022  t = {t:.4f} d  ({rel:+.4f} d from mid-transit)",
        "tpf_movie_subtitle": "Flip pages to watch the aperture-integrated flux vary across the transit. Pipeline aperture outlined in red.",
        "section_oddeven": "Odd / Even Transits",
        "section_observations": "Observations Summary",
        "obs_ndata": "Data cadences",
        "obs_ntransits": "Transits observed",
        "obs_sector": "Sector/Quarter",
        "obs_mission": "Mission",
        "obs_baseline": "Baseline",
        "obs_cadence": "Cadence",
        "obs_days_label": "days",
        "obs_depth": "Depth (MAP)",
        "obs_snr": "Transit SNR",
        "odd_label": "Odd transits",
        "even_label": "Even transits",
        "best_period_label": "Best Period: {period:.4f} d",
        "mcmc_best_fit": "MCMC Best Fit",
        "mcmc_credible_band": "1\u03c3 predictive band",
        "mcmc_posterior_draws": "Posterior draws ({n})",

        # Parameter table
        "col_parameter": "Parameter",
        "col_value": "Median \u00b1 1\u03c3",
        "col_unit": "Unit",

        "fitted_header": "Fitted Parameters (posterior)",
        "derived_header": "Derived Quantities",
        "derived_depth": "Transit depth",
        "derived_impact": "Impact parameter b",
        "derived_t14": "Duration T14",
        "derived_rp_rjup": "Planet radius Rp",
        "derived_inc_deg": "Inclination i",

        # Fit quality
        "chi2_reduced": "Reduced \u03c7\u00b2",
        "bic_label": "BIC",
        "aic_label": "AIC",
        "rms_residuals": "RMS residuals",
        "n_data_points": "Data points",
        "n_free_params": "Free parameters",

        # Diagnostics page
        "section_traces": "Walker Traces",
        "section_corner": "Posterior Distributions",
        "step_number": "Step (thinned)",

        # Convergence info
        "convergence_title": "Convergence Summary",
        "n_walkers": "Walkers",
        "n_steps": "Steps",
        "burn_in": "Burn-in",
        "autocorr": "Autocorrelation \u03c4",
        "acceptance": "Mean acceptance",
        "n_eff": "Effective samples",
        "not_estimated": "N/A",

        # Axes (shared between SPA plots + PDF report)
        "time_bjd": "Time [BJD]",
        "normalized_flux": "Normalised Flux",
        "period_days": "Period [days]",
        "power": "Power",
        "phase_days": "Phase [days]",
        "residuals": "Residuals (O-C)",
        "spaghetti_label": "Posterior draws ({n})",
        "transit_depth_ppm": "Depth: {depth:.0f} ppm",
        "snr_label": "SNR: {snr:.1f}",
        "rp_rs_label": "Rp/Rs = {val:.4f}",
        "a_rs_label": "a/Rs = {val:.2f}",
        "inc_label": "i = {val:.2f} deg",

        # ── SPA (analysis.html) plot titles, axes, legends ──────────
        # Kept separate from the report keys above so we can tweak the
        # SPA wording without touching the PDF report copy.
        "ui_title_raw_lc":             "Stitched raw lightcurve $-$ {target}",
        "ui_title_periodogram":        "Box Least Squares periodogram",
        "ui_title_folded_initial":     "Initial folded lightcurve $(P = {period:.4f}\\,\\mathrm{{d}})$",
        "ui_title_folded_with_model":  "Folded lightcurve with best-fit transit model",
        "ui_title_oddeven":            "Odd / even transit comparison",
        "ui_axis_time_obs":            "Observation time (days, gaps compressed)",
        "ui_axis_time_btjd":           "Time (BTJD $-$ 2{,}457{,}000)",
        "ui_axis_time_bkjd":           "Time (BKJD $-$ 2{,}454{,}833)",
        "ui_axis_time_generic":        "Time (days)",
        "ui_axis_flux":                "Normalised flux $F/\\langle F\\rangle$",
        "ui_axis_phase":               "Phase $\\phi$ (days from mid-transit)",
        "ui_axis_phase_short":         "Phase (days)",
        "ui_axis_period":              "Orbital period (days)",
        "ui_axis_power":               "BLS power",
        "ui_legend_folded_data":       "Folded data",
        "ui_legend_best_fit_map":      "Best-fit model (MAP)",
        "ui_legend_peak_period":       "$P = {period:.4f}\\,\\mathrm{{d}}$",
        "ui_odd_transits":             "Odd transits",
        "ui_even_transits":            "Even transits",
    },

    # ══════════════════════════════════════════════════════════════
    #  French
    # ══════════════════════════════════════════════════════════════
    "fr": {
        "report_title": "Rapport d'Analyse de Transit",
        "report_header": "Rapport Exoplot",
        "made_by": "R\u00e9alis\u00e9 par {url}  \u2022  {date}",
        "page_summary": "R\u00e9sum\u00e9 de l'Ajustement",
        "page_diagnostics": "Diagnostics MCMC",
        "generated_by": "G\u00e9n\u00e9r\u00e9 par {name}",
        "generated_on": "G\u00e9n\u00e9r\u00e9 le {date}",
        "target_label": "Cible : {target}",

        "section_lightcurve": "Courbe de Lumi\u00e8re Nettoy\u00e9e",
        "section_raw_lightcurve": "Courbe de Lumi\u00e8re Brute (SAP / PDCSAP)",
        "section_periodogram": "P\u00e9riodogramme BLS",
        "section_transit_fit": "Transit Repli\u00e9 en Phase (P = {period:.4f} j)",
        "section_parameters": "Param\u00e8tres D\u00e9riv\u00e9s",
        "section_pixel_file": "Fichier Pixel (s\u00e9quence)",
        "section_spaghetti": "Tirages Post\u00e9rieurs",
        "section_mcmc_results": "R\u00e9sultats MCMC",
        "section_fit_quality": "Qualit\u00e9 de l'ajustement",
        "tpf_unavailable": "Fichier pixel indisponible",
        "tpf_median_label": "M\u00e9dian",
        "tpf_frame_label": "t = {t:.3f} j",
        "tpf_aperture_label": "Ouverture pipeline",
        "tpf_movie_title": "Fichier Pixel \u2014 Film image par image",
        "tpf_movie_frame": "Image {i}/{n}  \u2022  t = {t:.4f} j  ({rel:+.4f} j du transit)",
        "tpf_movie_subtitle": "Feuilletez les pages pour visualiser la variation de flux pendant le transit. Ouverture pipeline en rouge.",
        "section_oddeven": "Transits Pairs / Impairs",
        "section_observations": "R\u00e9sum\u00e9 des Observations",
        "obs_ndata": "Cadences",
        "obs_ntransits": "Transits observ\u00e9s",
        "obs_sector": "Secteur/Trimestre",
        "obs_mission": "Mission",
        "obs_baseline": "Ligne de base",
        "obs_cadence": "Cadence",
        "obs_days_label": "jours",
        "obs_depth": "Profondeur (MAP)",
        "obs_snr": "SNR du transit",
        "odd_label": "Transits impairs",
        "even_label": "Transits pairs",
        "best_period_label": "Meilleure p\u00e9riode : {period:.4f} j",
        "mcmc_best_fit": "Meilleur ajustement MCMC",
        "mcmc_credible_band": "Bande pr\u00e9dictive 1\u03c3",
        "mcmc_posterior_draws": "Tirages post\u00e9rieurs ({n})",

        "col_parameter": "Param\u00e8tre",
        "col_value": "M\u00e9diane \u00b1 1\u03c3",
        "col_unit": "Unit\u00e9",

        "fitted_header": "Param\u00e8tres Ajust\u00e9s (post\u00e9rieur)",
        "derived_header": "Grandeurs D\u00e9riv\u00e9es",
        "derived_depth": "Profondeur du transit",
        "derived_impact": "Param\u00e8tre d'impact b",
        "derived_t14": "Dur\u00e9e T14",
        "derived_rp_rjup": "Rayon plan\u00e9taire Rp",
        "derived_inc_deg": "Inclinaison i",

        "chi2_reduced": "\u03c7\u00b2 r\u00e9duit",
        "bic_label": "BIC",
        "aic_label": "AIC",
        "rms_residuals": "RMS r\u00e9sidus",
        "n_data_points": "Points de donn\u00e9es",
        "n_free_params": "Param\u00e8tres libres",

        "section_traces": "Traces des Marcheurs",
        "section_corner": "Distributions Post\u00e9rieures",
        "step_number": "Pas (aminci)",

        "convergence_title": "R\u00e9sum\u00e9 de Convergence",
        "n_walkers": "Marcheurs",
        "n_steps": "Pas",
        "burn_in": "Burn-in",
        "autocorr": "Autocorr\u00e9lation \u03c4",
        "acceptance": "Acceptance moy.",
        "n_eff": "\u00c9chantillons effectifs",
        "not_estimated": "N/D",

        "time_bjd": "Temps [BJD]",
        "normalized_flux": "Flux Normalis\u00e9",
        "period_days": "P\u00e9riode [jours]",
        "power": "Puissance",
        "phase_days": "Phase [jours]",
        "residuals": "R\u00e9sidus (O-C)",
        "spaghetti_label": "Tirages post\u00e9rieurs ({n})",
        "transit_depth_ppm": "Profondeur : {depth:.0f} ppm",
        "snr_label": "S/B : {snr:.1f}",
        "rp_rs_label": "Rp/Rs = {val:.4f}",
        "a_rs_label": "a/Rs = {val:.2f}",
        "inc_label": "i = {val:.2f} deg",

        # ── SPA (analysis.html) ────────────────────────────────────
        "ui_title_raw_lc":             "Courbe de lumi\u00e8re brute $-$ {target}",
        "ui_title_periodogram":        "P\u00e9riodogramme BLS",
        "ui_title_folded_initial":     "Courbe repli\u00e9e initiale $(P = {period:.4f}\\,\\mathrm{{j}})$",
        "ui_title_folded_with_model":  "Courbe repli\u00e9e avec mod\u00e8le de transit ajust\u00e9",
        "ui_title_oddeven":            "Comparaison des transits pairs / impairs",
        "ui_axis_time_obs":            "Temps d'observation (jours, trous compress\u00e9s)",
        "ui_axis_time_btjd":           "Temps (BTJD $-$ 2{,}457{,}000)",
        "ui_axis_time_bkjd":           "Temps (BKJD $-$ 2{,}454{,}833)",
        "ui_axis_time_generic":        "Temps (jours)",
        "ui_axis_flux":                "Flux normalis\u00e9 $F/\\langle F\\rangle$",
        "ui_axis_phase":               "Phase $\\phi$ (jours depuis le milieu du transit)",
        "ui_axis_phase_short":         "Phase (jours)",
        "ui_axis_period":              "P\u00e9riode orbitale (jours)",
        "ui_axis_power":               "Puissance BLS",
        "ui_legend_folded_data":       "Donn\u00e9es repli\u00e9es",
        "ui_legend_best_fit_map":      "Mod\u00e8le ajust\u00e9 (MAP)",
        "ui_legend_peak_period":       "$P = {period:.4f}\\,\\mathrm{{j}}$",
        "ui_odd_transits":             "Transits impairs",
        "ui_even_transits":            "Transits pairs",
    },
}

#: Single source of truth for the subset of locales the whole app
#: recognises.  Keep in lock-step with ``static/js/i18n.js``.
SUPPORTED_LOCALES: tuple[str, ...] = ("en", "fr")

_REFERENCE_KEYS = frozenset(_STRINGS["en"].keys())

_current_locale = "en"

_UNICODE_TO_LATEX = {
    "\u00b1": r"$\pm$",
    "\u03c3": r"$\sigma$",
    "\u03c4": r"$\tau$",
    "\u2212": r"$-$",
}

#: Exoplot now ships only ``en`` / ``fr`` and both render cleanly via
#: pdfTeX — kept for API compatibility with the rest of the codebase.
_LATEX_INCOMPATIBLE_LOCALES: frozenset[str] = frozenset()


def normalise_locale(code: str | None) -> str:
    """Return a safe locale code, coercing anything unsupported to ``en``."""
    if code is None:
        return _current_locale
    code = str(code).lower().strip()
    if code in _STRINGS:
        return code
    # Accept browser-style tags such as "fr-CA", "en_US", …
    short = code.split("-")[0].split("_")[0]
    return short if short in _STRINGS else "en"


def set_locale(code: str) -> None:
    """Set the default locale for subsequent :func:`t` calls.

    Raises:
        ValueError: If *code* is not among the supported locales.
    """
    global _current_locale
    code = normalise_locale(code)
    if code not in _STRINGS:
        raise ValueError(
            f"Unknown locale '{code}'. Supported: {', '.join(_STRINGS)}"
        )
    _current_locale = code


def get_locale() -> str:
    return _current_locale


def is_latex_compatible(locale: str | None = None) -> bool:
    """Return ``False`` for locales whose scripts can't render via pdfTeX.

    With the EN+FR-only contract this is always ``True``, but we keep
    the hook so ``ReportGenerator`` can stay locale-agnostic."""
    loc = locale or _current_locale
    return loc not in _LATEX_INCOMPATIBLE_LOCALES


def _latex_safe(text: str) -> str:
    """Replace Unicode math symbols with LaTeX equivalents."""
    for char, repl in _UNICODE_TO_LATEX.items():
        text = text.replace(char, repl)
    return text


def t(key: str, locale: str | None = None, latex: bool = False,
      **kwargs) -> str:
    """
    Translate *key* into the requested (or current) locale.

    Parameters
    ----------
    key     : translation key
    locale  : override locale (falls back to ``en`` if unknown)
    latex   : replace Unicode math symbols (``±``, ``σ``, ``τ`` …) with
              their LaTeX equivalents so the string is safe for pdfTeX.
    **kwargs: forwarded to :meth:`str.format`
    """
    loc = normalise_locale(locale) if locale else _current_locale
    pack = _STRINGS.get(loc, _STRINGS["en"])
    raw = pack.get(key) or _STRINGS["en"].get(key) or key
    try:
        result = raw.format(**kwargs) if kwargs else raw
    except (KeyError, IndexError):
        result = raw
    if latex:
        result = _latex_safe(result)
    return result


def available_locales() -> list[str]:
    """Return the list of supported locale codes."""
    return list(_STRINGS.keys())


def available_keys() -> list[str]:
    """Return the list of all translation keys (based on the English reference)."""
    return sorted(_REFERENCE_KEYS)
