"""
Backend Internationalisation (i18n)
-----------------------------------
Provides translated strings for PDF reports and any server-side text.
Language codes mirror the frontend i18n.js: en, fr, es, de, ja, zh, ru, pt, ko.

Usage:
    from modules.i18n import t, set_locale
    set_locale("fr")
    t("report_title")           # → "Rapport d'Analyse de Transit"
    t("report_title", "en")     # → "Transit Analysis Report"

Author: S. Wittmann
Repository: https://github.com/SimonWtmn/Exoplot
"""

_STRINGS: dict[str, dict[str, str]] = {
    "en": {
        # Report structure
        "report_title": "Transit Analysis Report",
        "page_summary": "Transit Fit Summary",
        "page_diagnostics": "MCMC Diagnostics",
        "generated_by": "Generated by {name}",
        "generated_on": "Generated on {date}",
        "target_label": "Target: {target}",

        # Summary page sections
        "section_lightcurve": "Cleaned Lightcurve",
        "section_periodogram": "Box Least Squares Periodogram",
        "section_transit_fit": "Phase-Folded Transit (P = {period:.4f} d)",
        "section_parameters": "Derived Parameters",
        "best_period_label": "Best Period: {period:.4f} d",
        "mcmc_best_fit": "MCMC Best Fit",
        "mcmc_credible_band": "1σ predictive band",

        # Table
        "col_parameter": "Parameter",
        "col_value": "Median ± 1σ",

        # Diagnostics page
        "section_traces": "Walker Traces",
        "section_corner": "Posterior Distributions",
        "step_number": "Step (thinned)",

        # Convergence info
        "convergence_title": "Convergence Summary",
        "n_walkers": "Walkers",
        "n_steps": "Steps",
        "burn_in": "Burn-in",
        "autocorr": "Autocorrelation τ",
        "acceptance": "Mean acceptance",
        "n_eff": "Effective samples",
        "not_estimated": "N/A",

        # Axes
        "time_bjd": "Time [BJD]",
        "normalized_flux": "Normalised Flux",
        "period_days": "Period [days]",
        "power": "Power",
        "phase_days": "Phase [days]",
        "residuals": "Residuals (O-C)",
        "spaghetti_label": "Posterior draws ({n})",
        "transit_depth_ppm": "Depth: {depth:.0f} ppm",
        "snr_label": "SNR: {snr:.1f}",
        "rp_rs_label": "Rp/Rs = {val:.4f}",
        "a_rs_label": "a/Rs = {val:.2f}",
        "inc_label": "i = {val:.2f} deg",
    },
    "fr": {
        "report_title": "Rapport d'Analyse de Transit",
        "page_summary": "Résumé de l'Ajustement",
        "page_diagnostics": "Diagnostics MCMC",
        "generated_by": "Généré par {name}",
        "generated_on": "Généré le {date}",
        "target_label": "Cible : {target}",

        "section_lightcurve": "Courbe de Lumière Nettoyée",
        "section_periodogram": "Périodogramme BLS",
        "section_transit_fit": "Transit Replié en Phase (P = {period:.4f} j)",
        "section_parameters": "Paramètres Dérivés",
        "best_period_label": "Meilleure période : {period:.4f} j",
        "mcmc_best_fit": "Meilleur ajustement MCMC",
        "mcmc_credible_band": "Bande prédictive 1σ",

        "col_parameter": "Paramètre",
        "col_value": "Médiane ± 1σ",

        "section_traces": "Traces des Marcheurs",
        "section_corner": "Distributions Postérieures",
        "step_number": "Pas (aminci)",

        "convergence_title": "Résumé de Convergence",
        "n_walkers": "Marcheurs",
        "n_steps": "Pas",
        "burn_in": "Burn-in",
        "autocorr": "Autocorrélation τ",
        "acceptance": "Acceptance moy.",
        "n_eff": "Échantillons effectifs",
        "not_estimated": "N/D",

        "time_bjd": "Temps [BJD]",
        "normalized_flux": "Flux Normalisé",
        "period_days": "Période [jours]",
        "power": "Puissance",
        "phase_days": "Phase [jours]",
        "residuals": "Résidus (O-C)",
        "spaghetti_label": "Tirages postérieurs ({n})",
        "transit_depth_ppm": "Profondeur : {depth:.0f} ppm",
        "snr_label": "S/B : {snr:.1f}",
        "rp_rs_label": "Rp/Rs = {val:.4f}",
        "a_rs_label": "a/Rs = {val:.2f}",
        "inc_label": "i = {val:.2f} deg",
    },
    "es": {
        "report_title": "Informe de Análisis de Tránsito",
        "page_summary": "Resumen del Ajuste",
        "page_diagnostics": "Diagnósticos MCMC",
        "generated_by": "Generado por {name}",
        "generated_on": "Generado el {date}",
        "target_label": "Objetivo: {target}",

        "section_lightcurve": "Curva de Luz Limpia",
        "section_periodogram": "Periodograma BLS",
        "section_transit_fit": "Tránsito Plegado (P = {period:.4f} d)",
        "section_parameters": "Parámetros Derivados",
        "best_period_label": "Mejor período: {period:.4f} d",
        "mcmc_best_fit": "Mejor ajuste MCMC",

        "col_parameter": "Parámetro",
        "col_value": "Mediana ± 1σ",

        "section_traces": "Trazas de los Caminantes",
        "section_corner": "Distribuciones Posteriores",
        "step_number": "Paso (adelgazado)",

        "convergence_title": "Resumen de Convergencia",
        "n_walkers": "Caminantes",
        "n_steps": "Pasos",
        "burn_in": "Burn-in",
        "autocorr": "Autocorrelación τ",
        "acceptance": "Aceptación media",
        "n_eff": "Muestras efectivas",
        "not_estimated": "N/D",

        "time_bjd": "Tiempo [BJD]",
        "normalized_flux": "Flujo Normalizado",
        "period_days": "Período [días]",
        "power": "Potencia",
        "phase_days": "Fase [días]",
        "residuals": "Residuos (O-C)",
        "spaghetti_label": "Muestras posteriores ({n})",
        "transit_depth_ppm": "Profundidad: {depth:.0f} ppm",
        "snr_label": "SNR: {snr:.1f}",
        "rp_rs_label": "Rp/Rs = {val:.4f}",
        "a_rs_label": "a/Rs = {val:.2f}",
        "inc_label": "i = {val:.2f} deg",
    },
    "de": {
        "report_title": "Transit-Analysebericht",
        "page_summary": "Zusammenfassung der Anpassung",
        "page_diagnostics": "MCMC-Diagnostik",
        "generated_by": "Erstellt von {name}",
        "generated_on": "Erstellt am {date}",
        "target_label": "Ziel: {target}",

        "section_lightcurve": "Bereinigte Lichtkurve",
        "section_periodogram": "BLS-Periodogramm",
        "section_transit_fit": "Phasengefalteter Transit (P = {period:.4f} d)",
        "section_parameters": "Abgeleitete Parameter",
        "best_period_label": "Beste Periode: {period:.4f} d",
        "mcmc_best_fit": "MCMC-Bestanpassung",

        "col_parameter": "Parameter",
        "col_value": "Median ± 1σ",

        "section_traces": "Walker-Spuren",
        "section_corner": "Posteriorverteilungen",
        "step_number": "Schritt (ausgedünnt)",

        "convergence_title": "Konvergenzübersicht",
        "n_walkers": "Walker",
        "n_steps": "Schritte",
        "burn_in": "Burn-in",
        "autocorr": "Autokorrelation τ",
        "acceptance": "Mittlere Akzeptanz",
        "n_eff": "Effektive Stichproben",
        "not_estimated": "k. A.",

        "time_bjd": "Zeit [BJD]",
        "normalized_flux": "Normierter Fluss",
        "period_days": "Periode [Tage]",
        "power": "Leistung",
        "phase_days": "Phase [Tage]",
        "residuals": "Residuen (O-C)",
        "spaghetti_label": "Posterior-Ziehungen ({n})",
        "transit_depth_ppm": "Tiefe: {depth:.0f} ppm",
        "snr_label": "SNR: {snr:.1f}",
        "rp_rs_label": "Rp/Rs = {val:.4f}",
        "a_rs_label": "a/Rs = {val:.2f}",
        "inc_label": "i = {val:.2f} deg",
    },
    "ja": {
        "report_title": "トランジット解析レポート",
        "page_summary": "フィット概要",
        "page_diagnostics": "MCMC 診断",
        "generated_by": "{name} により生成",
        "generated_on": "生成日: {date}",
        "target_label": "対象: {target}",

        "section_lightcurve": "クリーニング済み光度曲線",
        "section_periodogram": "BLS ペリオドグラム",
        "section_transit_fit": "位相折り返しトランジット (P = {period:.4f} d)",
        "section_parameters": "導出パラメータ",
        "best_period_label": "最良周期: {period:.4f} d",
        "mcmc_best_fit": "MCMC 最良フィット",

        "col_parameter": "パラメータ",
        "col_value": "中央値 ± 1σ",

        "section_traces": "ウォーカートレース",
        "section_corner": "事後分布",
        "step_number": "ステップ（間引き後）",

        "convergence_title": "収束まとめ",
        "n_walkers": "ウォーカー数",
        "n_steps": "ステップ数",
        "burn_in": "バーンイン",
        "autocorr": "自己相関 τ",
        "acceptance": "平均受容率",
        "n_eff": "有効サンプル数",
        "not_estimated": "N/A",

        "time_bjd": "時刻 [BJD]",
        "normalized_flux": "規格化フラックス",
        "period_days": "周期 [日]",
        "power": "パワー",
        "phase_days": "位相 [日]",
        "residuals": "残差 (O-C)",
        "spaghetti_label": "事後抽出 ({n})",
        "transit_depth_ppm": "深さ: {depth:.0f} ppm",
        "snr_label": "SNR: {snr:.1f}",
        "rp_rs_label": "Rp/Rs = {val:.4f}",
        "a_rs_label": "a/Rs = {val:.2f}",
        "inc_label": "i = {val:.2f} deg",
    },
    "zh": {
        "report_title": "凌星分析报告",
        "page_summary": "拟合摘要",
        "page_diagnostics": "MCMC 诊断",
        "generated_by": "由 {name} 生成",
        "generated_on": "生成于 {date}",
        "target_label": "目标: {target}",

        "section_lightcurve": "清洗后的光变曲线",
        "section_periodogram": "BLS 周期图",
        "section_transit_fit": "相位折叠凌星 (P = {period:.4f} d)",
        "section_parameters": "推导参数",
        "best_period_label": "最佳周期: {period:.4f} d",
        "mcmc_best_fit": "MCMC 最佳拟合",

        "col_parameter": "参数",
        "col_value": "中位数 ± 1σ",

        "section_traces": "行者轨迹",
        "section_corner": "后验分布",
        "step_number": "步 (稀释后)",

        "convergence_title": "收敛摘要",
        "n_walkers": "行者数",
        "n_steps": "步数",
        "burn_in": "预热期",
        "autocorr": "自相关 τ",
        "acceptance": "平均接受率",
        "n_eff": "有效样本数",
        "not_estimated": "N/A",

        "time_bjd": "时间 [BJD]",
        "normalized_flux": "归一化通量",
        "period_days": "周期 [天]",
        "power": "功率",
        "phase_days": "相位 [天]",
        "residuals": "残差 (O-C)",
        "spaghetti_label": "后验抽样 ({n})",
        "transit_depth_ppm": "深度: {depth:.0f} ppm",
        "snr_label": "SNR: {snr:.1f}",
        "rp_rs_label": "Rp/Rs = {val:.4f}",
        "a_rs_label": "a/Rs = {val:.2f}",
        "inc_label": "i = {val:.2f} deg",
    },
    "ru": {
        "report_title": "Отчёт об анализе транзита",
        "page_summary": "Сводка подгонки",
        "page_diagnostics": "Диагностика MCMC",
        "generated_by": "Создано {name}",
        "generated_on": "Создано {date}",
        "target_label": "Цель: {target}",

        "section_lightcurve": "Очищенная кривая блеска",
        "section_periodogram": "Периодограмма BLS",
        "section_transit_fit": "Сложенный транзит (P = {period:.4f} д)",
        "section_parameters": "Полученные параметры",
        "best_period_label": "Лучший период: {period:.4f} д",
        "mcmc_best_fit": "Лучшая подгонка MCMC",

        "col_parameter": "Параметр",
        "col_value": "Медиана ± 1σ",

        "section_traces": "Следы блуждальщиков",
        "section_corner": "Апостериорные распределения",
        "step_number": "Шаг (прореженный)",

        "convergence_title": "Сводка сходимости",
        "n_walkers": "Блуждальщиков",
        "n_steps": "Шагов",
        "burn_in": "Прогрев",
        "autocorr": "Автокорреляция τ",
        "acceptance": "Средняя доля принятия",
        "n_eff": "Эффективных выборок",
        "not_estimated": "Н/Д",

        "time_bjd": "Время [BJD]",
        "normalized_flux": "Нормированный поток",
        "period_days": "Период [дни]",
        "power": "Мощность",
        "phase_days": "Фаза [дни]",
        "residuals": "Остатки (O-C)",
        "spaghetti_label": "Апостериорные выборки ({n})",
        "transit_depth_ppm": "Глубина: {depth:.0f} ppm",
        "snr_label": "SNR: {snr:.1f}",
        "rp_rs_label": "Rp/Rs = {val:.4f}",
        "a_rs_label": "a/Rs = {val:.2f}",
        "inc_label": "i = {val:.2f} deg",
    },
    "pt": {
        "report_title": "Relatório de Análise de Trânsito",
        "page_summary": "Resumo do Ajuste",
        "page_diagnostics": "Diagnósticos MCMC",
        "generated_by": "Gerado por {name}",
        "generated_on": "Gerado em {date}",
        "target_label": "Alvo: {target}",

        "section_lightcurve": "Curva de Luz Limpa",
        "section_periodogram": "Periodograma BLS",
        "section_transit_fit": "Trânsito Dobrado (P = {period:.4f} d)",
        "section_parameters": "Parâmetros Derivados",
        "best_period_label": "Melhor período: {period:.4f} d",
        "mcmc_best_fit": "Melhor ajuste MCMC",

        "col_parameter": "Parâmetro",
        "col_value": "Mediana ± 1σ",

        "section_traces": "Traços dos Caminhantes",
        "section_corner": "Distribuições Posteriores",
        "step_number": "Passo (rarefeito)",

        "convergence_title": "Resumo de Convergência",
        "n_walkers": "Caminhantes",
        "n_steps": "Passos",
        "burn_in": "Burn-in",
        "autocorr": "Autocorrelação τ",
        "acceptance": "Aceitação média",
        "n_eff": "Amostras efetivas",
        "not_estimated": "N/D",

        "time_bjd": "Tempo [BJD]",
        "normalized_flux": "Fluxo Normalizado",
        "period_days": "Período [dias]",
        "power": "Potência",
        "phase_days": "Fase [dias]",
        "residuals": "Residuais (O-C)",
        "spaghetti_label": "Amostras posteriores ({n})",
        "transit_depth_ppm": "Profundidade: {depth:.0f} ppm",
        "snr_label": "SNR: {snr:.1f}",
        "rp_rs_label": "Rp/Rs = {val:.4f}",
        "a_rs_label": "a/Rs = {val:.2f}",
        "inc_label": "i = {val:.2f} deg",
    },
    "ko": {
        "report_title": "통과 분석 보고서",
        "page_summary": "피팅 요약",
        "page_diagnostics": "MCMC 진단",
        "generated_by": "{name}에서 생성",
        "generated_on": "생성일: {date}",
        "target_label": "대상: {target}",

        "section_lightcurve": "정리된 밝기 곡선",
        "section_periodogram": "BLS 주기도",
        "section_transit_fit": "위상 접힌 통과 (P = {period:.4f} d)",
        "section_parameters": "도출 매개변수",
        "best_period_label": "최적 주기: {period:.4f} d",
        "mcmc_best_fit": "MCMC 최적 피팅",

        "col_parameter": "매개변수",
        "col_value": "중앙값 ± 1σ",

        "section_traces": "워커 추적",
        "section_corner": "사후 분포",
        "step_number": "스텝 (간격 후)",

        "convergence_title": "수렴 요약",
        "n_walkers": "워커 수",
        "n_steps": "스텝 수",
        "burn_in": "번인",
        "autocorr": "자기상관 τ",
        "acceptance": "평균 수용률",
        "n_eff": "유효 샘플 수",
        "not_estimated": "N/A",

        "time_bjd": "시간 [BJD]",
        "normalized_flux": "정규화 플럭스",
        "period_days": "주기 [일]",
        "power": "파워",
        "phase_days": "위상 [일]",
        "residuals": "잔차 (O-C)",
        "spaghetti_label": "사후 추출 ({n})",
        "transit_depth_ppm": "깊이: {depth:.0f} ppm",
        "snr_label": "SNR: {snr:.1f}",
        "rp_rs_label": "Rp/Rs = {val:.4f}",
        "a_rs_label": "a/Rs = {val:.2f}",
        "inc_label": "i = {val:.2f} deg",
    },
}

_REFERENCE_KEYS = frozenset(_STRINGS["en"].keys())

_current_locale = "en"

_UNICODE_TO_LATEX = {
    "\u00b1": r"$\pm$",
    "\u03c3": r"$\sigma$",
    "\u03c4": r"$\tau$",
    "\u2212": r"$-$",
}

_LATEX_INCOMPATIBLE_LOCALES = {"ja", "zh", "ko", "ru"}


def set_locale(code: str):
    """Set the default locale for subsequent t() calls.
    
    Raises:
        ValueError: If *code* is not among the supported locales.
    """
    global _current_locale
    if code not in _STRINGS:
        raise ValueError(
            f"Unknown locale '{code}'. Supported: {', '.join(_STRINGS)}"
        )
    _current_locale = code


def get_locale() -> str:
    return _current_locale


def is_latex_compatible(locale: str | None = None) -> bool:
    """Return False for locales whose scripts can't be rendered by pdfTeX."""
    return (locale or _current_locale) not in _LATEX_INCOMPATIBLE_LOCALES


def _latex_safe(text: str) -> str:
    """Replace Unicode math symbols with LaTeX equivalents."""
    for char, repl in _UNICODE_TO_LATEX.items():
        text = text.replace(char, repl)
    return text


def t(key: str, locale: str | None = None, latex: bool = False,
      **kwargs) -> str:
    """
    Translate *key* into the requested (or current) locale.

    Parameters
    ----------
    key     : translation key
    locale  : override locale
    latex   : if True, replace Unicode math symbols (±, σ, τ …) with
              their LaTeX equivalents so the string is safe for pdfTeX.
    **kwargs: forwarded to ``str.format()``
    """
    loc = locale or _current_locale
    pack = _STRINGS.get(loc, _STRINGS["en"])
    raw = pack.get(key) or _STRINGS["en"].get(key) or key
    try:
        result = raw.format(**kwargs) if kwargs else raw
    except (KeyError, IndexError):
        result = raw
    if latex:
        result = _latex_safe(result)
    return result


def available_locales() -> list[str]:
    """Return the list of supported locale codes."""
    return list(_STRINGS.keys())


def available_keys() -> list[str]:
    """Return the list of all translation keys (based on the English reference)."""
    return sorted(_REFERENCE_KEYS)
