"""
MCMC Transit Fitting Utilities
------------------------------
Provides the `TransitFitter` class to run Markov Chain Monte Carlo simulations 
on folded lightcurves to extract physical planetary parameters.

Author: S. Wittmann
Repository: https://github.com/SimonWtmn/Exoplot_ENS
"""

import numpy as np
import emcee
import batman
from scipy.optimize import minimize

# Import all the physical boundaries and assumptions from our constants file
from .constants import (
    MCMC_BOUNDS, MCMC_X0, MCMC_LABELS, 
    LIMB_DARKENING_COEFFS, LIMB_DARKENING_MODEL, 
    ECCENTRICITY, ARG_PERI
)

class TransitFitter:
    """
    A class to handle the mathematical modeling of a planetary transit and 
    the statistical MCMC exploration of the parameter space.
    """

    def __init__(self, time: np.ndarray, flux: np.ndarray, flux_err: np.ndarray, period: float):
        """
        Initializes the fitter with the folded observational data.
        
        Args:
            time (np.ndarray): The folded time array (usually in Julian Days).
            flux (np.ndarray): The normalized flux array.
            flux_err (np.ndarray): The estimated error for each flux measurement.
            period (float): The orbital period of the planet in days.
        """
        self.time = time
        self.flux = flux
        self.flux_err = flux_err
        self.period = period
        
        # State variables to hold the outputs of the MCMC process
        self.best_fit_params = None
        self.sampler = None
        self.flat_samples = None
        self.results_summary = None

    # ===========================================================
    # Internal Math & Modeling Methods
    # ===========================================================

    def _check_bounds(self, params: list) -> bool:
        """
        Checks if the proposed MCMC step falls within physically realistic boundaries.
        
        Args:
            params (list): The proposed parameters [rp/rs, inclination, a/rs, t0].
            
        Returns:
            bool: True if parameters are valid, False if they violate physics/priors.
        """
        # 1. Check strict numerical boundaries defined in constants.py
        for p, (low, high) in zip(params, MCMC_BOUNDS):
            if not (low <= p <= high):
                return False

        # 2. Extract parameters for physical geometry check
        rp_rs, inc_deg, a_rs, _ = params
        
        # Calculate impact parameter 'b'
        b = a_rs * np.cos(np.radians(inc_deg))
        
        # If b > 1 + rp/rs, the planet completely misses the stellar disk (no transit)
        if b > 1 + rp_rs:
            return False

        return True

    def _make_transit_model(self, params: list, t_array: np.ndarray) -> np.ndarray:
        """
        Generates a synthetic lightcurve using the Batman package based on the given parameters.
        """
        rp_rs, inc_deg, a_rs, t0 = params

        # Initialize the Batman parameter object
        transit_params = batman.TransitParams()
        transit_params.t0 = t0
        transit_params.per = self.period
        transit_params.rp = rp_rs
        transit_params.a = a_rs
        transit_params.inc = inc_deg
        
        # Apply static assumptions from constants.py
        transit_params.ecc = ECCENTRICITY
        transit_params.w = ARG_PERI
        transit_params.u = LIMB_DARKENING_COEFFS
        transit_params.limb_dark = LIMB_DARKENING_MODEL

        # Generate and return the synthetic flux
        model = batman.TransitModel(transit_params, t_array)
        return model.light_curve(transit_params)

    def _log_likelihood(self, params: list) -> float:
        """
        Calculates the log-likelihood that the observed data matches the synthetic model
        generated by the proposed parameters.
        """
        # Reject immediately if parameters are physically impossible
        if not self._check_bounds(params):
            return -np.inf

        try:
            model_flux = self._make_transit_model(params, self.time)
        except Exception:
            # Catch Batman calculation failures
            return -np.inf

        # Ensure the model didn't produce NaNs or Infinity
        if not np.all(np.isfinite(model_flux)):
            return -np.inf

        # Calculate Chi-squared (how far the model is from the data, weighted by error)
        chi2 = np.sum(((self.flux - model_flux) / self.flux_err) ** 2)

        if not np.isfinite(chi2):
            return -np.inf

        # Return the log-likelihood
        return -0.5 * chi2

    def _neg_loglike(self, params: list) -> float:
        """
        Returns the negative log-likelihood. 
        Used purely for the initial Scipy minimization function.
        """
        val = -self._log_likelihood(params)
        if not np.isfinite(val):
            return 1e10  # Return a massive penalty instead of infinity for the optimizer
        return val

    # ===========================================================
    # Execution Methods
    # ===========================================================

    def optimize_initial_guess(self):
        """
        Uses the Powell minimization algorithm to find a decent starting point 
        for the MCMC walkers, drastically reducing convergence time.
        """
        result = minimize(
            self._neg_loglike, 
            MCMC_X0, 
            bounds=MCMC_BOUNDS, 
            method="Powell"
        )
        
        if not result.success:
            raise RuntimeError("Initial optimization failed: " + result.message)
            
        self.best_fit_params = result.x
        return self.best_fit_params

    def run_mcmc(self, nwalkers: int = 32, nsteps: int = 5000, progress_callback=None):
        """
        Executes the Markov Chain Monte Carlo simulation.
        
        Args:
            nwalkers (int): Number of independent MCMC chains.
            nsteps (int): Number of steps each walker will take.
            progress_callback (function): An optional function to call to report progress 
                                          (very useful for web loading bars!).
        """
        ndim = len(MCMC_LABELS)

        # 1. Find the best starting position
        self.optimize_initial_guess()

        # 2. Cluster the walkers in a tight ball around the best fit
        p0 = self.best_fit_params + 1e-3 * np.random.randn(nwalkers, ndim)

        # 3. Initialize the Emcee sampler
        self.sampler = emcee.EnsembleSampler(nwalkers, ndim, self._log_likelihood)

        # 4. Run the simulation
        # We use a loop so we can report progress back to the user/frontend
        for step, _ in enumerate(self.sampler.sample(p0, iterations=nsteps, progress=False)):
            if step % 10 == 0 and progress_callback is not None:
                progress_callback(step, nsteps)

        if progress_callback is not None:
            progress_callback(nsteps, nsteps)

        # 5. Extract the results
        # We discard the first 100 steps (burn-in phase) and thin the chain by 10 to reduce correlation
        self.flat_samples = self.sampler.get_chain(discard=100, thin=10, flat=True)
        self.results_summary = self._compute_summary()

        return self.results_summary

    def _compute_summary(self) -> dict:
        """
        Calculates the median and confidence intervals (16th and 84th percentiles) 
        for each parameter based on the flat posterior samples.
        """
        results = {}
        ndim = self.flat_samples.shape[1]
        
        for i in range(ndim):
            # Calculate the 1-sigma spread
            q16, q50, q84 = np.percentile(self.flat_samples[:, i], [16, 50, 84])
            
            # Store as: Median, Upper Error (+), Lower Error (-)
            results[MCMC_LABELS[i]] = (q50, q84 - q50, q50 - q16)
            
        return results

    def get_best_model_curve(self, num_points: int = 5000) -> tuple:
        """
        Generates a smooth, high-resolution transit curve based on the finalized 
        MCMC results. This is used strictly for plotting the final line on the UI.
        
        Returns:
            tuple: (smooth_time_array, synthetic_flux_array)
        """
        if self.results_summary is None:
            raise ValueError("MCMC has not been run yet. Call run_mcmc() first.")

        # Extract just the median values from the results dictionary
        final_params = [self.results_summary[label][0] for label in MCMC_LABELS]
        
        # Generate a smooth, evenly spaced time array
        smooth_time = np.linspace(min(self.time), max(self.time), num_points)
        
        # Generate the model flux
        synthetic_flux = self._make_transit_model(final_params, smooth_time)
        
        return smooth_time, synthetic_flux