"""
PDF Report Generation Utilities
-------------------------------
Provides the `ReportGenerator` class to create publication-quality, 
LaTeX-rendered PDF summary sheets for exoplanet catalogs and MCMC fits 
using Matplotlib and GridSpec.

Author: S. Wittmann
Repository: https://github.com/SimonWtmn/Exoplot_ENS
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.backends.backend_pdf import PdfPages
import corner
from datetime import datetime
from pathlib import Path

class ReportGenerator:
    """
    Generates professional PDF reports.
    """

    def __init__(self, website_name="Exoplot", website_url="www.exoplot.ens.fr", use_latex=True):
        self.website_name = website_name
        self.website_url = website_url
        self.use_latex = use_latex
        self._setup_matplotlib()
        self.results_dir = Path(__file__).parent.parent / "results"
        self.results_dir.mkdir(parents=True, exist_ok=True)

    def _setup_matplotlib(self):
        plt.rcParams.update({
            'font.family': 'serif',
            'font.size': 10,
            'axes.labelsize': 12,
            'axes.titlesize': 14,
            'xtick.labelsize': 10,
            'ytick.labelsize': 10,
            'legend.fontsize': 10,
            'lines.linewidth': 1.5,
            'lines.markersize': 4,
            'figure.dpi': 300,
        })
        
        if self.use_latex:
            plt.rcParams.update({
                'text.usetex': True,
                'font.serif': ['Computer Modern Roman'],
            })
        else:
            plt.rcParams.update({'text.usetex': False})

    def _add_header_footer(self, fig, target_name, report_type):
        # Header
        fig.text(0.5, 0.98, f"{target_name} - {report_type}", 
                 ha='center', va='center', fontsize=20, fontweight='bold')
        fig.text(0.5, 0.96, f"Generated by {self.website_name} | {datetime.now().strftime('%Y-%m-%d')}", 
                 ha='center', va='center', fontsize=10, color='gray')
        
        # Footer
        fig.text(0.05, 0.02, f"Target: {target_name}", ha='left', fontsize=9, color='gray')
        fig.text(0.95, 0.02, self.website_url, ha='right', fontsize=9, color='gray')


    # ===========================================================
    # REPORT 1: MCMC Summary Report
    # ===========================================================

    def generate_mcmc_summary_report(self, filename: str, analyzer, fitter):
        """
        Generates a 1-page TESS-style MCMC Validation Report with Lightcurves and Results.
        """
        labels = list(fitter.results_summary.keys())

        filepath = self.results_dir / filename
        with PdfPages(filepath) as pdf:
            fig1 = plt.figure(figsize=(8.27, 11.69)) # Standard A4 Size
            self._add_header_footer(fig1, analyzer.target_name, "Transit Fit Summary")
            
            gs1 = gridspec.GridSpec(4, 1, figure=fig1, height_ratios=[1, 1, 1.5, 1.2])
            
            # 1. Raw Lightcurve
            ax1 = fig1.add_subplot(gs1[0])
            raw_time = analyzer.clean_lc.time.value
            raw_flux = analyzer.clean_lc.flux.value
            raw_err = analyzer.clean_lc.flux_err.value if analyzer.clean_lc.flux_err is not None else np.full_like(raw_flux, np.median(raw_flux) * 0.01)
            
            ax1.errorbar(raw_time, raw_flux, yerr=raw_err, fmt='.', color='#2c3e50', ecolor='#bdc3c7', 
                         markersize=2, alpha=0.5, capsize=0, elinewidth=0.8)
            ax1.set_title("1. Cleaned Lightcurve", fontweight='bold')
            ax1.set_xlabel("Time [BJD]")
            ax1.set_ylabel("Normalized Flux")
            ax1.grid(True, alpha=0.3)

            # 2. Periodogram
            ax2 = fig1.add_subplot(gs1[1])
            ax2.plot(analyzer.periodogram.period.value, analyzer.periodogram.power.value, color='#2980b9', linewidth=1.5)
            ax2.axvline(analyzer.best_period, color='#e74c3c', linestyle='--', alpha=0.8, label=f"Best Period: {analyzer.best_period:.4f} d")
            ax2.set_title("2. Box Least Squares (BLS) Periodogram", fontweight='bold')
            ax2.set_xlabel("Period [days]")
            ax2.set_ylabel("Power")
            ax2.set_xscale('log')
            ax2.legend()
            ax2.grid(True, alpha=0.3)

            # 3. Phase-Folded Transit Fit 
            ax3 = fig1.add_subplot(gs1[2])
            fold_time = analyzer.folded_lc.time.value
            fold_flux = analyzer.folded_lc.flux.value
            fold_err = analyzer.folded_lc.flux_err.value if analyzer.folded_lc.flux_err is not None else np.full_like(fold_flux, np.median(fold_flux) * 0.01)
            
            model_time, model_flux = fitter.get_best_model_curve(phase_folded=True)
            
            ax3.errorbar(fold_time, fold_flux, yerr=fold_err, fmt='.', color='#2c3e50', ecolor='#bdc3c7', 
                         markersize=3.5, alpha=0.6, capsize=0, zorder=1, elinewidth=1)
            ax3.plot(model_time, model_flux, color='#e74c3c', linewidth=2.5, zorder=2, label='MCMC Best Fit')
            
            zoom = fitter.period * 0.1
            ax3.set_xlim(-zoom, zoom)
            ax3.set_title(f"3. Phase-Folded Transit Fit (P = {fitter.period:.4f} d)", fontweight='bold')
            ax3.set_xlabel("Phase [days]")
            ax3.set_ylabel("Normalized Flux")
            ax3.legend()
            ax3.grid(True, alpha=0.3)

            # 4. Results Table
            ax4 = fig1.add_subplot(gs1[3])
            ax4.axis('off') 
            ax4.set_title("4. MCMC Derived Parameters", pad=0, fontweight='bold')
            
            cell_text = []
            for label in labels:
                med, upper, lower = fitter.results_summary[label]
                if self.use_latex:
                    val_str = f"${med:.5f}_{{-{lower:.5f}}}^{{+{upper:.5f}}}$"
                else:
                    val_str = f"{med:.5f} (+{upper:.5f} / -{lower:.5f})"
                cell_text.append([label, val_str])
                
            table = ax4.table(
                cellText=cell_text, 
                colLabels=['Parameter', r'Value (Median $\pm 1\sigma$)'], 
                loc='center', 
                cellLoc='center',
                bbox=[0.1, 0.0, 0.8, 0.8] 
            )
            
            table.auto_set_font_size(False)
            table.set_fontsize(11)

            for (row, col), cell in table.get_celld().items():
                cell.set_linewidth(0.5)
                cell.set_edgecolor('#cccccc') 
                if row == 0:
                    cell.set_text_props(weight='bold')
                    cell.set_facecolor('#ecf0f1') 
                elif row % 2 == 0:
                    cell.set_facecolor('#fafafa')
            fig1.tight_layout(rect=[0, 0.05, 1, 0.95], h_pad=3.0)
            pdf.savefig(fig1)
            plt.close(fig1)


    # ===========================================================
    # REPORT 2: MCMC Diagnostic Report
    # ===========================================================
    def generate_mcmc_diagnostic_report(self, filename: str, analyzer, fitter):
        """
        Generates a 1-page Diagnostic Report.
        Strict A4 Portrait Format.
        """
        labels = list(fitter.results_summary.keys())
        ndim = len(labels)

        filepath = self.results_dir / filename
        with PdfPages(filepath) as pdf:
            fig2 = plt.figure(figsize=(8.27, 11.69))
            self._add_header_footer(fig2, analyzer.target_name, "MCMC Diagnostics")
            
            flat_samples = fitter.flat_samples
            
            # --- 1. CORNER PLOT (Bottom section) ---
            with plt.rc_context({'xtick.labelsize': 8, 'ytick.labelsize': 8}):
                corner_fig = corner.corner(
                    flat_samples, 
                    labels=labels, 
                    quantiles=[0.16, 0.5, 0.84],
                    show_titles=True, 
                    title_kwargs={"fontsize": 9},
                    label_kwargs={"fontsize": 9},
                    color='#1f77b4',
                    hist_kwargs={'linewidth': 1.5},
                    quiet=True, 
                    plot_datapoints=False, 
                    plot_density=True,     
                    fig=fig2 
                )
            
            # Ajustement pour laisser de la place aux traces en haut
            plt.subplots_adjust(bottom=0.08, top=0.60, left=0.12, right=0.95)
            
            # --- 2. TRACE PLOTS (Top section) ---
            gs_traces = gridspec.GridSpec(ndim, 1, figure=fig2, top=0.92, bottom=0.66, hspace=0.15)
            
            try:
                # Thinning by 50 makes it lighter
                chain = fitter.sampler.get_chain(thin=50) 
            except Exception:
                chain = None
                
            for i in range(ndim):
                ax = fig2.add_subplot(gs_traces[i])
                ax.set_rasterization_zorder(1)
                
                if chain is not None:
                    n_walkers = chain.shape[1]
                    colors = plt.cm.plasma(np.linspace(0, 1, n_walkers))
                    
                    for w in range(n_walkers):
                        ax.plot(chain[:, w, i], color=colors[w], alpha=0.5, linewidth=0.5, zorder=0)
                else:
                    ax.plot(fitter.flat_samples[::5, i], color='#1f77b4', alpha=0.3, linewidth=0.5, zorder=0)
                    
                ax.set_ylabel(labels[i], fontsize=9)
                ax.tick_params(axis='both', which='major', labelsize=8)
                
                if i < ndim - 1:
                    ax.set_xticklabels([])
                else:
                    ax.set_xlabel("Step Number (Thinned)", fontsize=9)
                    
                ax.grid(True, alpha=0.3)
            pdf.savefig(fig2, dpi=150) 
            plt.close(fig2)


    # ===========================================================
    # REPORT 3: Catalog Summary Report
    # ===========================================================

    def generate_catalog_report(self, filename: str, df: pd.DataFrame, plot_configs: list, title="Exoplanet Population Summary"):
        """
        Generates a multi-graph catalog summary sheet based on user-selected templates.
        """
        filepath = self.results_dir / filename
        with PdfPages(filepath) as pdf:
            fig = plt.figure(figsize=(11.69, 8.27)) # Landscape A4 Size
            self._add_header_footer(fig, "Catalog Sample", title)
            
            n_plots = len(plot_configs)
            
            if n_plots == 1:
                gs = gridspec.GridSpec(1, 1, figure=fig)
            elif n_plots == 2:
                gs = gridspec.GridSpec(1, 2, figure=fig)
            elif n_plots <= 4:
                gs = gridspec.GridSpec(2, 2, figure=fig)
            else:
                raise ValueError("Maximum 4 plots per summary sheet supported.")

            for i, config in enumerate(plot_configs):
                ax = fig.add_subplot(gs[i])
                
                x_col, y_col = config.get('x'), config.get('y')
                clean_df = df.dropna(subset=[x_col, y_col]) if y_col else df.dropna(subset=[x_col])
                
                if config.get('type') == 'scatter':
                    ax.scatter(clean_df[x_col], clean_df[y_col], alpha=0.6, s=15, color='#1f77b4', edgecolor='black', linewidth=0.5)
                    if config.get('log_x'): ax.set_xscale('log')
                    if config.get('log_y'): ax.set_yscale('log')
                    ax.set_ylabel(y_col.replace('_', ' ').title())
                
                elif config.get('type') == 'histogram':
                    ax.hist(clean_df[x_col], bins=30, color='#ff7f0e', edgecolor='black')
                    ax.set_ylabel("Count")
                    
                ax.set_xlabel(x_col.replace('_', ' ').title())
                ax.grid(True, alpha=0.3)

            fig.tight_layout(rect=[0, 0.05, 1, 0.94], w_pad=2.0, h_pad=2.0)
            pdf.savefig(fig)
            plt.close(fig)